before:
  hooks:
  - go mod download
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'
    - '^build:'
    - '^chore:'
    - '^Merge'
release:
  prerelease: auto
env:
  - CGO_ENABLED=0
builds:
- id: caddy
  dir: caddy/mercure
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 5
    - 6
    - 7
archives:
- builds:
  - caddy
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
  - COPYRIGHT
  - LICENSE
  - README.md
  - Caddyfile
  - Caddyfile.dev
  format_overrides:
  - goos: windows
    format: zip
dockers:
- ids:
  - caddy
  goos: linux
  goarch: amd64
  image_templates:
  - 'ghcr.io/devmachine-fr/mercure/mercure:{{ .Tag }}-amd64'
  - 'ghcr.io/devmachine-fr/mercure/mercure:v{{ .Major }}-amd64'
  - 'ghcr.io/devmachine-fr/mercure/mercure:v{{ .Major }}.{{ .Minor }}-amd64'
  - 'ghcr.io/devmachine-fr/mercure/mercure:latest-amd64'
  use: buildx
  build_flag_templates:
  - "--platform=linux/amd64"
  extra_files:
  - Caddyfile
  - Caddyfile.dev
- ids:
  - caddy
  goos: linux
  goarch: arm64
  image_templates:
  - 'ghcr.io/devmachine-fr/mercure/mercure:{{ .Tag }}-arm64v8'
  - 'ghcr.io/devmachine-fr/mercure/mercure:v{{ .Major }}-arm64v8'
  - 'ghcr.io/devmachine-fr/mercure/mercure:v{{ .Major }}.{{ .Minor }}-arm64v8'
  - 'ghcr.io/devmachine-fr/mercure/mercure:latest-arm64v8'
  use: buildx
  build_flag_templates:
  - "--platform=linux/arm64/v8"
  extra_files:
  - Caddyfile
  - Caddyfile.dev
docker_manifests:
- name_template: ghcr.io/devmachine-fr/mercure/mercure:{{ .Tag }}
  image_templates:
  - ghcr.io/devmachine-fr/mercure/mercure:{{ .Tag }}-amd64
  - ghcr.io/devmachine-fr/mercure/mercure:{{ .Tag }}-arm64v8
- name_template: ghcr.io/devmachine-fr/mercure/mercure:v{{ .Major }}
  image_templates:
  - ghcr.io/devmachine-fr/mercure/mercure:v{{ .Major }}-amd64
  - ghcr.io/devmachine-fr/mercure/mercure:v{{ .Major }}-arm64v8
- name_template: ghcr.io/devmachine-fr/mercure/mercure:v{{ .Major }}.{{ .Minor }}
  image_templates:
  - ghcr.io/devmachine-fr/mercure/mercure:v{{ .Major }}.{{ .Minor }}-amd64
  - ghcr.io/devmachine-fr/mercure/mercure:v{{ .Major }}.{{ .Minor }}-arm64v8
- name_template: ghcr.io/devmachine-fr/mercure/mercure:latest
  image_templates:
  - ghcr.io/devmachine-fr/mercure/mercure:latest-amd64
  - ghcr.io/devmachine-fr/mercure/mercure:latest-arm64v8
signs:
  - artifacts: checksum
    args: ["--batch", "--output", "${signature}", "--detach-sign", "${artifact}"]
