name: Release Hub

on:
  push:
    tags:
      - 'v*'
    branches:
      - '*'
  pull_request:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: |
            go.sum
            caddy/go.sum

      - name: Login to Docker Hub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Set GoReleaser Git tags
        run: |
          tags=$(git tag --list --sort=-version:refname 'v*')
          echo "GORELEASER_CURRENT_TAG=$(awk 'NR==1 {print;exit}' <<< "$tags")"  >> "$GITHUB_ENV"
          echo "GORELEASER_PREVIOUS_TAG=$(awk 'NR==2 {print;exit}' <<< "$tags")"  >> "$GITHUB_ENV"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean ${{startsWith(github.ref, 'refs/tags/v') && '' || '--snapshot'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Display version
        run: dist/caddy_linux_amd64_v1/mercure version

      - name: Upload snapshot
        if: ${{!startsWith(github.ref, 'refs/tags/v')}}
        uses: actions/upload-artifact@v3
        with:
          name: snapshot
          path: dist/*
          retention-days: 1
